select * from customer limit 20;
--q1.What is the total revenue generated by male vs female customers

select gender,sum(purchase_amount) as revenue from customer group by gender;


--q2.which customers used a discount but still spent more than the average purchase amount

select customer_id,purchase_amount from customer where discount_applied='Yes' and purchase_amount>(select avg(purchase_amount) from customer);


--q3.Which are the top 5 products wuth the highest average review rating?
Select item_purchased, round(avg(review_rating::numeric),2 ) as "Average Review Rating"  from customer group by item_purchased order by avg(review_rating) desc limit 5;


--q4.Compare the average Purchase amounts between Standard and Express Shipping.
Select shipping_type,avg(purchase_amount) as "Comparision between Standard and Express Shipping" from customer where shipping_type in ('Standard','Express') group by shipping_type;


--q5.Do Subscribed customers spend more? Compare avergae spend and atotal revenue between subscribed and non-subscribes.
select subscription_status,count(customer_id) as total_customers,round(avg(purchase_amount),2) as avg_spend,round(sum(purchase_amount),2) total_revenue from customer group by subscription_status order by total_revenue,avg_spend desc;



--q6.which 5 products have the highest percentage of purchase wiith discount applied?
Select item_purchased,round(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate from customer group by item_purchased order by discount_rate desc limit 5;


--q7.Segement customer into new ,returning and loyal based on their total numbeer of previous purchase and show the count of each segement.
with customer_type as (
select customer_id,previous_purchases,
case
when previous_purchases=1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from customer
)

select customer_segment,count(*) as "Number of Customers"
from customer_type 
group by customer_segment;


--q8.What are the top 3 most purchased products within each category?
with item_counts as(
select category,item_purchased, count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) Desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank,category,item_purchased,total_orders
from item_counts 
where item_rank<=3;


--q9-Are customers who are repeat buyers (more than 5 previous purchase) also likely to subscribe?

select subscription_status ,count(customer_id) as "Repeat buyer"
from customer 
where previous_purchases>5
group by subscription_status


--q10: What is the revenue contribution of each age group ?
Select age_group,sum(purchase_amount) as total_revenue from customer 
group by age_group
order by total_revenue desc;


